boot_count: 1257
clean_exit: true
com_baud: 115200
com_timeout: 5
controller_feedback_interval: 50
last_lens: L086
lens:
  L084:
    debug_keypoints:
    - - -22.78
      - 0.74
      - -1.01
      - 0.0
    - - -20.18
      - -4.3
      - 0.21
      - 0.0
    - - -17.98
      - -6.3
      - 1.21
      - 0.0
    - - -14.48
      - -6.4
      - 2.31
      - 0.0
    - - -11.58
      - -4.7
      - 3.21
      - 0.0
    - - -9.08
      - -2.85
      - 4.11
      - 0.0
    - - -5.08
      - 0.5
      - 5.31
      - 0.0
    - - -0.58
      - 3.9
      - 5.91
      - 0.0
    - - 3.92
      - 6.45
      - 5.81
      - 0.0
    - - 8.42
      - 7.7
      - 4.61
      - 0.0
    - - 11.42
      - 7.9
      - 3.51
      - 0.0
    - - 14.42
      - 7.95
      - 2.51
      - 0.0
    - - 17.92
      - 7.6
      - 1.11
      - 0.0
    - - 21.92
      - 6.9
      - -0.49
      - 0.0
    - - 24.42
      - 6.45
      - -1.39
      - 0.0
    - - 27.92
      - 5.65
      - -2.69
      - 0.0
    - - 30.92
      - 5.0
      - -3.69
      - 0.0
    - - 32.92
      - 4.3
      - -4.59
      - 0.0
    - - 34.92
      - 3.8
      - -5.29
      - 0.0
    description: 40x 6.3-252mm 1/1.8"
    filter1:
      name: IR CUT
      state_off:
      - M113 P1
      - M116 P0
      - M117 P1
      - G04 P1
      - M113 P0
      state_on:
      - M113 P1
      - M116 P1
      - M117 P0
      - G04 P1
      - M113 P0
    filter2:
      name: NIR
      state_off:
      - M113 P1
      - M114 P0
      - M115 P1
      - G04 P1
      - M113 P0
      state_on:
      - M113 P1
      - M114 P1
      - M115 P0
      - G04 P1
      - M113 P0
    iris:
      close: G90 G1 A-5 F1000
      open: G90 G1 A0 F1000
    lens_sku: L084-MZFD-6.3Z252-DIRECT
    limit_sensor:
      led_off: M120 P0
      led_on: M120 P1
    motor:
      curves:
        focus_inf:
          color: '#0000FF'
          name: Focus infinity
          pulloff: 0
          x:
          - -22.78
          - -20.18
          - -17.98
          - -14.48
          - -11.58
          - -9.08
          - -5.08
          - -0.58
          - 3.92
          - 8.42
          - 11.42
          - 14.42
          - 17.92
          - 21.92
          - 24.42
          - 27.92
          - 30.92
          - 32.92
          - 34.92
          y:
          - 6.72
          - -0.038
          - -3.178
          - -4.602
          - -3.656
          - -2.104
          - 0.922
          - 4.157
          - 6.634
          - 7.794
          - 7.992
          - 8.05
          - 7.619
          - 6.903
          - 6.458
          - 5.676
          - 5.032
          - 4.347
          - 3.822
        focus_near:
          color: '#00FF00'
          name: Focus near
          pulloff: 0
          x: &id001
          - -22.78
          - -20.18
          - -17.98
          - -14.48
          - -11.58
          - -9.08
          - -5.08
          - -0.58
          - 3.92
          - 8.42
          - 11.42
          - 14.42
          - 17.92
          - 21.92
          - 24.42
          - 27.92
          - 30.92
          - 32.92
          - 34.92
          y:
          - 0.783
          - -4.304
          - -6.273
          - -6.313
          - -4.728
          - -2.824
          - 0.526
          - 3.955
          - 6.52
          - 7.741
          - 7.949
          - 8.003
          - 7.603
          - 6.9
          - 6.446
          - 5.675
          - 5.034
          - 4.353
          - 3.824
        zoom_correction:
          color: '#606060'
          name: Zoom correction
          pulloff: 0
          x: *id001
          y:
          - -1.01
          - 0.21
          - 1.21
          - 2.31
          - 3.21
          - 4.11
          - 5.31
          - 5.91
          - 5.81
          - 4.61
          - 3.51
          - 2.51
          - 1.11
          - -0.49
          - -1.39
          - -2.69
          - -3.69
          - -4.59
          - -5.29
      default_speed: 1000
      function:
        axis_a: Iris
        axis_x: Zoom1
        axis_y: Focus
        axis_z: Zoom2
      homing_pulloff:
        value: 0.5
      interpolate_count: 250
      range:
        axis_a: null
        axis_x: null
        axis_y: null
        axis_z: null
      reverse:
        axis_a: false
        axis_x: false
        axis_y: false
        axis_z: false
      speed_list: 2000 1500 *1000 500 200 100 50 10
      step_list: 0.01 0.05 *0.1 0.5 1.0 5.0
    preset:
      p1: 34.92 3.75 -5.29 0.0
      p2: 14.8 7.97 2.43 0.0
      p3: -2.5 2.77 5.79 0.0
      p4: -13.5 -4.42 2.59 0.0
      p5: -22.78 6.74 -1.31 0.0
    specs:
      focal_length_max: 252
      focal_length_min: 6.3
      image_circle: 9.2
      lpm: 250
  L086:
    debug_keypoints:
    - - -11.67
      - -3.2
      - -2.4
      - 0.297
    - - -7.87
      - 0.8
      - -4.1
      - 0.297
    - - -2.87
      - 3.0
      - -1.6
      - 0.297
    - - 2.23
      - 4.7
      - 1.4
      - 0.297
    - - 6.53
      - 5.3
      - 3.1
      - 0.0
    - - 12.63
      - 5.9
      - 5.0
      - 0.297
    description: 18x 6.8-120mm 1/1.8"
    filter1:
      name: IR CUT
      state_off: G90 G1 A0.7 F1
      state_on: G90 G1 A0.3 F1
    iris:
      close: M114 P0
      open: M114 P1
    lens_sku: L086-MZFD-6.8Z120-DIRECT
    limit_sensor:
      led_off: M120 P0
      led_on: M120 P1
    motor:
      curves:
        focus_inf:
          color: '#0000FF'
          name: Focus infinity
          pulloff: 0
          x:
          - -11.67
          - -7.87
          - -2.87
          - 2.23
          - 6.53
          - 12.63
          y:
          - -2.4
          - -4.1
          - -1.6
          - 1.4
          - 3.1
          - 5.0
        focus_near:
          color: '#00FF00'
          name: Focus near
          pulloff: 0
          x:
          - -11.67
          - -7.87
          - -2.87
          - 2.23
          - 6.53
          - 12.63
          y:
          - -2.4
          - -4.1
          - -1.6
          - 1.4
          - 3.1
          - 5.0
        zoom_correction:
          color: '#606060'
          name: Zoom correction
          pulloff: 0
          x:
          - -11.67
          - -7.87
          - -2.87
          - 2.23
          - 6.53
          - 12.63
          y:
          - -3.2
          - 0.51
          - 3.034
          - 4.643
          - 5.142
          - 5.745
      default_speed: 1000
      function:
        axis_a: null
        axis_x: Zoom1
        axis_y: Zoom2
        axis_z: Focus
      homing_pulloff:
        value: 0
      interpolate_count: 50
      invert:
        axis_a: false
        axis_x: false
        axis_y: false
        axis_z: false
      range:
        axis_a: null
        axis_x: null
        axis_y: null
        axis_z: null
      speed_list: 2000 1500 *1000 500 200 100 50 10
      step_list: 0.01 0.05 *0.1 0.5 1.0 5.0
    preset:
      p1: 12.024 5.826 4.923 0.0
      p2: 6.407 5.166 3.043 0.0
      p3: 0.321 3.826 0.084 0.0
      p4: -5.838 1.853 -3.182 0.0
      p5: -10.843 -1.924 -3.229 0.0
    specs:
      focal_length_max: 120
      focal_length_min: 6.8
      image_circle: 9.2
      lpm: 250
  L117:
    debug_keypoints:
    - - -4.1
      - 5.484
      - 4.89
      - 0.0
    - - -3.5
      - 3.884
      - 5.19
      - 0.0
    - - -2.5
      - 1.084
      - 5.19
      - 0.0
    - - -0.2
      - -3.216
      - 5.19
      - 0.0
    - - 4.6
      - -5.716
      - 5.39
      - 0.0
    - - 14.8
      - -1.906
      - 5.53
      - 0.0
    - - 30.8
      - 0.867
      - 2.73
      - 0.0
    - - 43.02
      - -1.161
      - -1.24
      - 0.0
    - - 45.94
      - -1.761
      - -2.14
      - 0.0
    description: 32x 6.5-212mm 1/1.8"
    filter1:
      name: IR CUT
      state_off:
      - M113 P1
      - M116 P0
      - M117 P1
      - G04 P1
      - M113 P0
      state_on:
      - M113 P1
      - M116 P1
      - M117 P0
      - G04 P1
      - M113 P0
    filter2:
      name: NIR
      state_off:
      - M113 P1
      - M114 P0
      - M115 P1
      - G04 P1
      - M113 P0
      state_on:
      - M113 P1
      - M114 P1
      - M115 P0
      - G04 P1
      - M113 P0
    iris:
      close: G90 G1 A-5 F1000
      open: G90 G1 A0 F1000
    lens_sku: L117-MZFD-6.5Z212-DIRECT
    limit_sensor:
      led_off: M120 P0
      led_on: M120 P1
    motor:
      curves:
        focus_inf:
          color: '#0000FF'
          name: Focus infinity
          pulloff: 0
          x: &id003
          - -4.1
          - -3.5
          - -2.5
          - -0.2
          - 4.6
          - 14.8
          - 30.8
          - 43.02
          - 45.94
          y:
          - 4.89
          - 5.19
          - 5.19
          - 5.19
          - 5.39
          - 5.53
          - 2.73
          - -1.24
          - -2.14
        zoom_correction:
          color: '#606060'
          name: Zoom correction
          pulloff: 0
          x: *id003
          y:
          - 5.551
          - 3.922
          - 1.156
          - -3.206
          - -5.663
          - -1.895
          - 0.893
          - -1.111
          - -1.726
      default_speed: 1000
      function:
        axis_a: Iris
        axis_x: Zoom1
        axis_y: Focus
        axis_z: Zoom2
      homing_pulloff:
        value: 0.5
      interpolate_count: 250
      range:
        axis_a: null
        axis_x: null
        axis_y: null
        axis_z: null
      reverse:
        axis_a: false
        axis_x: false
        axis_y: false
        axis_z: false
      speed_list: 2000 1500 *1000 500 200 100 50 10
      step_list: 0.01 0.05 *0.1 0.5 1.0 5.0
    preset:
      p1: 45.94 -1.761 -2.14 0.0
      p2: 30.8 0.837 2.73 0.0
      p3: 14.8 -1.856 5.53 0.0
      p4: 4.6 -5.616 5.39 0.0
      p5: -4.1 5.484 4.89 0.0
    specs:
      focal_length_max: 252
      focal_length_min: 6.3
      image_circle: 9.2
      lpm: 250
logging_level: DEBUG
port: COM299
remember_last_com_port: true
