boot_count: 242
clean_exit: true
com_baud: 115200
com_timeout: 5
controller_feedback_interval: 50
lens:
  L084:
    description: 40x 6.3-252mm 1/1.8"
    filter1:
      name: IR CUT
      state_off:
      - M113 P1
      - M116 P1
      - M117 P0
      - G04 P1
      - M113 P0
      state_on:
      - M113 P1
      - M116 P0
      - M117 P1
      - G04 P1
      - M113 P0
    filter2:
      name: NIR
      state_off:
      - M113 P1
      - M114 P1
      - M115 P0
      - G04 P1
      - M113 P0
      state_on:
      - M113 P1
      - M114 P0
      - M115 P1
      - G04 P1
      - M113 P0
    iris:
      close: G90 G1 A-5 F1000
      open: G90 G1 A0 F1000
    lens_sku: L084-MZFD-6.3Z252-DIRECT
    limit_sensor:
      led_off: M120 P0
      led_on: M120 P1
    motor:
      default_speed: 1000
      function:
        axis_a: Iris
        axis_x: Zoom1
        axis_y: Focus
        axis_z: Zoom2
      range:
        axis_a: null
        axis_x: null
        axis_y: null
        axis_z: null
      reverse:
        axis_a: false
        axis_x: false
        axis_y: false
        axis_z: false
      speed_list: 2000 1500 *1000 500 200 100 50 10
      step_list: 0.01 0.05 *0.1 0.5 1.0 5.0
    preset:
      p1: 35.0 3.31 -4.8 0.0
      p2: 19.3 6.11 0.2 0.0
      p3: -2.5 1.8 6.2 0.0
      p4: -8.7 -3.5 3.6 0.0
      p5: -16.7 -7.7 -2.5 0.0
    specs:
      focal_length_max: 252
      focal_length_min: 6.3
      image_circle: 9.2
      lpm: 250
  L085:
    description: 25x 5.3-130mm 1/2.7"
    filter1:
      name: IR CUT
      state_off: G90 G1 A0.7 F1
      state_on: G90 G1 A0.3 F1
    iris:
      close: M114 P0
      open: M114 P1
    lens_sku: L085-MZFD-5.3Z130-DIRECT
    limit_sensor:
      led_off: M120 P0
      led_on: M120 P1
    motor:
      default_speed: 1000
      function:
        axis_a: null
        axis_x: Zoom
        axis_y: Focus
        axis_z: null
      range:
        axis_a: null
        axis_x: null
        axis_y: null
        axis_z: null
      reverse:
        axis_a: false
        axis_x: false
        axis_y: false
        axis_z: false
      speed_list: 2000 1500 *1000 500 200 100 50 10
      step_list: 0.01 0.05 *0.1 0.5 1.0 5.0
    preset:
      p1: -9.0 0.3 -- --
      p2: -2.0 -1.9 -- --
      p3: 1.0 -3.0 -- --
      p4: 4.0 -3.8 -- --
      p5: 9.5 -1.3 -- --
    specs:
      focal_length_max: 130
      focal_length_min: 5.3
      image_circle: 6.8
      lpm: 250
  L086:
    description: 18x 6.8-120mm 1/1.8"
    filter1:
      name: IR CUT
      state_off: G90 G1 A0.7 F1
      state_on: G90 G1 A0.3 F1
    iris:
      close: M114 P0
      open: M114 P1
    lens_sku: L086-MZFD-6.8Z120-DIRECT
    limit_sensor:
      led_off: M120 P0
      led_on: M120 P1
    motor:
      default_speed: 1000
      function:
        axis_a: null
        axis_x: Zoom1
        axis_y: Zoom2
        axis_z: Focus
      range:
        axis_a: null
        axis_x: null
        axis_y: null
        axis_z: null
      reverse:
        axis_a: false
        axis_x: false
        axis_y: false
        axis_z: false
      speed_list: 2000 1500 *1000 500 200 100 50 10
      step_list: 0.01 0.05 *0.1 0.5 1.0 5.0
    preset:
      p1: -9.37 -4.8 -2.8 --
      p2: -3.3 -3.9 -0.5 --
      p3: 4.6 -1.4 3.8 --
      p4: 8.6 0.6 4.9 --
      p5: 11.6 3.5 2.7 --
    specs:
      focal_length_max: 120
      focal_length_min: 6.8
      image_circle: 9.2
      lpm: 250
logging_level: DEBUG
port: COM58
remember_last_com_port: true
