boot_count: 135
clean_exit: true
com_baud: 115200
com_timeout: 5
controller_feedback_interval: 50
lens:
  L086:
    description: 18x 6.8-120mm 1/1.8"
    filter1:
      name: IR CUT
      state_off: G90 G1 A1 F1
      state_on: G90 G1 A0 F1
    iris:
      close: M114 P0
      open: M114 P1
    lens_sku: L086-MZFD-6.8Z120-DIRECT
    limit_sensor:
      led_off: M120 P0
      led_on: M120 P1
    motor:
      default_speed: 1000
      function:
        axis_a: null
        axis_x: Zoom1
        axis_y: Zoom2
        axis_z: Focus
      range:
        axis_a: null
        axis_x: null
        axis_y: null
        axis_z: null
      reverse:
        axis_a: false
        axis_x: false
        axis_y: false
        axis_z: false
      speed_list: 2000 1500 *1000 500 200 100 50 10
      step_list: 0.01 0.05 *0.1 0.5 1.0 5.0
    specs:
      focal_length_max: 120
      focal_length_min: 6.8
      image_circle: 9.2
      lpm: 250
logging_level: DEBUG
port: COM20
preset:
  p1: -- -- -- --
  p2: -- -- -- --
  p3: -- -- -- --
  p4: -- -- -- --
  p5: -- -- -- --
remember_last_com_port: true
