boot_count: 1145
clean_exit: true
com_baud: 115200
com_timeout: 5
controller_feedback_interval: 50
last_lens: L084
lens:
  L084:
    debug_keypoints:
    - - -22.78
      - 0.54
      - -1.31
      - 0.0
    - - -21.534
      - -2.044
      - -0.476
      - 0.0
    - - -19.206
      - -5.485
      - 0.736
      - 0.0
    - - -17.46
      - -6.556
      - 1.428
      - 0.0
    - - -15.714
      - -6.694
      - 1.944
      - 0.0
    - - -12.804
      - -5.505
      - 2.808
      - 0.0
    - - -9.894
      - -3.493
      - 3.8
      - 0.0
    - - -6.402
      - -0.586
      - 4.933
      - 0.0
    - - -4.074
      - 1.351
      - 5.523
      - 0.0
    - - -0.582
      - 3.999
      - 6.004
      - 0.0
    - - 2.91
      - 6.025
      - 5.921
      - 0.0
    - - 6.402
      - 7.413
      - 5.335
      - 0.0
    - - 11.854
      - 8.17
      - 3.624
      - 0.0
    - - 14.561
      - 8.046
      - 2.541
      - 0.0
    - - 16.878
      - 7.736
      - 1.578
      - 0.0
    - - 19.788
      - 7.289
      - 0.406
      - 0.0
    - - 22.698
      - 6.832
      - -0.699
      - 0.0
    - - 26.19
      - 6.104
      - -1.971
      - 0.0
    - - 28.518
      - 5.597
      - -2.843
      - 0.0
    - - 30.264
      - 5.124
      - -3.516
      - 0.0
    - - 32.01
      - 4.624
      - -4.195
      - 0.0
    - - 34.92
      - 3.8
      - -5.29
      - 0.0
    description: 40x 6.3-252mm 1/1.8"
    filter1:
      name: IR CUT
      state_off:
      - M113 P1
      - M116 P0
      - M117 P1
      - G04 P1
      - M113 P0
      state_on:
      - M113 P1
      - M116 P1
      - M117 P0
      - G04 P1
      - M113 P0
    filter2:
      name: NIR
      state_off:
      - M113 P1
      - M114 P0
      - M115 P1
      - G04 P1
      - M113 P0
      state_on:
      - M113 P1
      - M114 P1
      - M115 P0
      - G04 P1
      - M113 P0
    iris:
      close: G90 G1 A-5 F1000
      open: G90 G1 A0 F1000
    lens_sku: L084-MZFD-6.3Z252-DIRECT
    limit_sensor:
      led_off: M120 P0
      led_on: M120 P1
    motor:
      curves:
        focus_inf:
          color: '#0000FF'
          name: Focus infinity
          pulloff: 0
          x: &id001
          - -22.78
          - -21.534
          - -19.206
          - -17.46
          - -15.714
          - -12.804
          - -9.894
          - -6.402
          - -4.074
          - -0.582
          - 2.91
          - 6.402
          - 11.854
          - 14.561
          - 16.878
          - 19.788
          - 22.698
          - 26.19
          - 28.518
          - 30.264
          - 32.01
          - 34.92
          y:
          - 6.428
          - 2.989
          - -1.631
          - -3.613
          - -4.516
          - -4.214
          - -2.662
          - -0.117
          - 1.676
          - 4.179
          - 6.166
          - 7.484
          - 8.207
          - 8.076
          - 7.801
          - 7.347
          - 6.85
          - 6.146
          - 5.602
          - 5.14
          - 4.639
          - 3.806
        focus_near:
          color: '#00FF00'
          name: Focus near
          pulloff: 0
          x:
          - -22.78
          - -21.534
          - -19.206
          - -17.46
          - -15.714
          - -12.804
          - -9.894
          - -6.402
          - -4.074
          - -0.582
          - 2.91
          - 6.402
          - 11.854
          - 14.561
          - 16.878
          - 19.788
          - 22.698
          - 26.19
          - 28.518
          - 30.264
          - 32.01
          - 34.92
          y:
          - 0.565
          - -2.07
          - -5.379
          - -6.476
          - -6.633
          - -5.492
          - -3.473
          - -0.592
          - 1.34
          - 3.987
          - 6.05
          - 7.411
          - 8.171
          - 8.062
          - 7.791
          - 7.336
          - 6.837
          - 6.144
          - 5.6
          - 5.136
          - 4.642
          - 3.81
        zoom_correction:
          color: '#606060'
          name: Zoom correction
          pulloff: 0
          x: *id001
          y:
          - -1.31
          - -0.476
          - 0.736
          - 1.428
          - 1.944
          - 2.808
          - 3.8
          - 4.933
          - 5.523
          - 6.004
          - 5.921
          - 5.335
          - 3.624
          - 2.541
          - 1.578
          - 0.406
          - -0.699
          - -1.971
          - -2.843
          - -3.516
          - -4.195
          - -5.29
      default_speed: 1000
      function:
        axis_a: Iris
        axis_x: Zoom1
        axis_y: Focus
        axis_z: Zoom2
      homing_pulloff:
        value: 0.5
      interpolate_count: 250
      range:
        axis_a: null
        axis_x: null
        axis_y: null
        axis_z: null
      reverse:
        axis_a: false
        axis_x: false
        axis_y: false
        axis_z: false
      speed_list: 2000 1500 *1000 500 200 100 50 10
      step_list: 0.01 0.05 *0.1 0.5 1.0 5.0
    preset:
      p1: 34.92 3.75 -5.29 0.0
      p2: 14.8 7.97 2.43 0.0
      p3: -2.5 2.77 5.79 0.0
      p4: -13.5 -4.42 2.59 0.0
      p5: -22.78 6.74 -1.31 0.0
    specs:
      focal_length_max: 252
      focal_length_min: 6.3
      image_circle: 9.2
      lpm: 250
  L086:
    debug_keypoints:
    - - -11.67
      - -3.2
      - -2.4
      - 0.297
    - - -7.87
      - 0.8
      - -4.1
      - 0.297
    - - -2.87
      - 3.0
      - -1.6
      - 0.297
    - - 2.23
      - 4.7
      - 1.4
      - 0.297
    - - 6.53
      - 5.3
      - 3.1
      - 0.0
    - - 12.63
      - 5.9
      - 5.0
      - 0.297
    description: 18x 6.8-120mm 1/1.8"
    filter1:
      name: IR CUT
      state_off: G90 G1 A0.7 F1
      state_on: G90 G1 A0.3 F1
    iris:
      close: M114 P0
      open: M114 P1
    lens_sku: L086-MZFD-6.8Z120-DIRECT
    limit_sensor:
      led_off: M120 P0
      led_on: M120 P1
    motor:
      curves:
        focus_inf:
          color: '#0000FF'
          name: Focus infinity
          pulloff: 0
          x: &id002
          - -11.67
          - -7.87
          - -2.87
          - 2.23
          - 6.53
          - 12.63
          y:
          - -2.4
          - -4.1
          - -1.6
          - 1.4
          - 3.1
          - 5.0
        zoom_correction:
          color: '#606060'
          name: Zoom correction
          pulloff: 0
          x: *id002
          y:
          - -3.2
          - 0.51
          - 3.034
          - 4.643
          - 5.142
          - 5.745
      default_speed: 1000
      function:
        axis_a: null
        axis_x: Zoom1
        axis_y: Zoom2
        axis_z: Focus
      homing_pulloff:
        value: 0
      interpolate_count: 50
      invert:
        axis_a: false
        axis_x: false
        axis_y: false
        axis_z: false
      range:
        axis_a: null
        axis_x: null
        axis_y: null
        axis_z: null
      speed_list: 2000 1500 *1000 500 200 100 50 10
      step_list: 0.01 0.05 *0.1 0.5 1.0 5.0
    preset:
      p1: 12.024 5.826 4.923 --
      p2: 6.407 5.166 3.043 --
      p3: 0.321 3.826 0.084 --
      p4: -5.838 1.853 -3.182 --
      p5: -10.843 -1.924 -3.229 --
    specs:
      focal_length_max: 120
      focal_length_min: 6.8
      image_circle: 9.2
      lpm: 250
  L117:
    debug_keypoints:
    - - -4.1
      - 5.484
      - 4.89
      - 0.0
    - - -3.5
      - 3.884
      - 5.19
      - 0.0
    - - -2.5
      - 1.084
      - 5.19
      - 0.0
    - - -0.2
      - -3.216
      - 5.19
      - 0.0
    - - 4.6
      - -5.716
      - 5.39
      - 0.0
    - - 14.8
      - -1.906
      - 5.53
      - 0.0
    - - 30.8
      - 0.867
      - 2.73
      - 0.0
    - - 43.02
      - -1.161
      - -1.24
      - 0.0
    - - 45.94
      - -1.761
      - -2.14
      - 0.0
    description: 32x 6.5-212mm 1/1.8"
    filter1:
      name: IR CUT
      state_off:
      - M113 P1
      - M116 P0
      - M117 P1
      - G04 P1
      - M113 P0
      state_on:
      - M113 P1
      - M116 P1
      - M117 P0
      - G04 P1
      - M113 P0
    filter2:
      name: NIR
      state_off:
      - M113 P1
      - M114 P0
      - M115 P1
      - G04 P1
      - M113 P0
      state_on:
      - M113 P1
      - M114 P1
      - M115 P0
      - G04 P1
      - M113 P0
    iris:
      close: G90 G1 A-5 F1000
      open: G90 G1 A0 F1000
    lens_sku: L117-MZFD-6.5Z212-DIRECT
    limit_sensor:
      led_off: M120 P0
      led_on: M120 P1
    motor:
      curves:
        focus_inf:
          color: '#0000FF'
          name: Focus infinity
          pulloff: 0
          x: &id003
          - -4.1
          - -3.5
          - -2.5
          - -0.2
          - 4.6
          - 14.8
          - 30.8
          - 43.02
          - 45.94
          y:
          - 4.89
          - 5.19
          - 5.19
          - 5.19
          - 5.39
          - 5.53
          - 2.73
          - -1.24
          - -2.14
        zoom_correction:
          color: '#606060'
          name: Zoom correction
          pulloff: 0
          x: *id003
          y:
          - 5.551
          - 3.922
          - 1.156
          - -3.206
          - -5.663
          - -1.895
          - 0.893
          - -1.111
          - -1.726
      default_speed: 1000
      function:
        axis_a: Iris
        axis_x: Zoom1
        axis_y: Focus
        axis_z: Zoom2
      homing_pulloff:
        value: 0.5
      interpolate_count: 250
      range:
        axis_a: null
        axis_x: null
        axis_y: null
        axis_z: null
      reverse:
        axis_a: false
        axis_x: false
        axis_y: false
        axis_z: false
      speed_list: 2000 1500 *1000 500 200 100 50 10
      step_list: 0.01 0.05 *0.1 0.5 1.0 5.0
    preset:
      p1: 45.94 -1.761 -2.14 0.0
      p2: 30.8 0.837 2.73 0.0
      p3: 14.8 -1.856 5.53 0.0
      p4: 4.6 -5.616 5.39 0.0
      p5: -4.1 5.484 4.89 0.0
    specs:
      focal_length_max: 252
      focal_length_min: 6.3
      image_circle: 9.2
      lpm: 250
logging_level: DEBUG
port: COM296
remember_last_com_port: true
