# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\test_pos_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.group_x_axis = QtWidgets.QGroupBox(self.centralwidget)
        self.group_x_axis.setEnabled(True)
        self.group_x_axis.setGeometry(QtCore.QRect(50, 50, 276, 79))
        self.group_x_axis.setObjectName("group_x_axis")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.group_x_axis)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_x_pos = QtWidgets.QLabel(self.group_x_axis)
        self.label_x_pos.setMinimumSize(QtCore.QSize(90, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_x_pos.setFont(font)
        self.label_x_pos.setObjectName("label_x_pos")
        self.verticalLayout_15.addWidget(self.label_x_pos)
        self.label_x_pi = QtWidgets.QLabel(self.group_x_axis)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_x_pi.setFont(font)
        self.label_x_pi.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_x_pi.setObjectName("label_x_pi")
        self.verticalLayout_15.addWidget(self.label_x_pi)
        self.horizontalLayout_13.addLayout(self.verticalLayout_15)
        self.gridLayout_2.addLayout(self.horizontalLayout_13, 0, 3, 1, 1)
        self.btn_x_right = QtWidgets.QPushButton(self.group_x_axis)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_x_right.sizePolicy().hasHeightForWidth())
        self.btn_x_right.setSizePolicy(sizePolicy)
        self.btn_x_right.setAutoRepeat(True)
        self.btn_x_right.setAutoRepeatInterval(50)
        self.btn_x_right.setObjectName("btn_x_right")
        self.gridLayout_2.addWidget(self.btn_x_right, 0, 1, 1, 1)
        self.btn_x_left = QtWidgets.QPushButton(self.group_x_axis)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_x_left.sizePolicy().hasHeightForWidth())
        self.btn_x_left.setSizePolicy(sizePolicy)
        self.btn_x_left.setAutoRepeat(True)
        self.btn_x_left.setAutoRepeatInterval(50)
        self.btn_x_left.setObjectName("btn_x_left")
        self.gridLayout_2.addWidget(self.btn_x_left, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.group_x_axis.setTitle(_translate("MainWindow", "X axis"))
        self.label_x_pos.setText(_translate("MainWindow", "---"))
        self.label_x_pi.setText(_translate("MainWindow", "---"))
        self.btn_x_right.setText(_translate("MainWindow", ">"))
        self.btn_x_left.setText(_translate("MainWindow", "<"))
