boot_count: 383
clean_exit: true
com_baud: 115200
com_timeout: 5
controller_feedback_interval: 50
lens:
  L084:
    description: 40x 6.3-252mm 1/1.8"
    filter1:
      name: IR CUT
      state_off: G90 G1 A0.7 F1
      state_on: G90 G1 A0.3 F1
    filter2:
      name: NIR
      state_off:
      - M113 P1
      - M114 P1
      - M115 P0
      - G04 P1
      - M113 P0
      state_on:
      - M113 P1
      - M114 P0
      - M115 P1
      - G04 P1
      - M113 P0
    iris:
      close: M114 P0
      open: M114 P1
    lens_sku: L085-MZFD-5.3Z130-DIRECT
    limit_sensor:
      led_off: M120 P0
      led_on: M120 P1
    motor:
      default_speed: 1000
      function:
        axis_a: null
        axis_x: Zoom
        axis_y: Focus
        axis_z: null
      homing_pulloff:
        value: 0
      invert:
        axis_a: false
        axis_x: false
        axis_y: false
        axis_z: false
      range:
        axis_a: null
        axis_x: null
        axis_y: null
        axis_z: null
      speed_list: 2000 1500 *1000 500 200 100 50 10
      step_list: 0.01 0.05 *0.1 0.5 1.0 5.0
    preset:
      p1: -9.0 0.3 -- --
      p2: -2.0 -1.9 -- --
      p3: 1.0 -3.0 -- --
      p4: 4.0 -3.8 -- --
      p5: 9.5 -1.3 -- --
    specs:
      focal_length_max: 130
      focal_length_min: 5.3
      image_circle: 6.8
      lpm: 250
  L086:
    description: 18x 6.8-120mm 1/1.8"
    filter1:
      name: IR CUT
      state_off: G90 G1 A0.7 F1
      state_on: G90 G1 A0.3 F1
    iris:
      close: M114 P0
      open: M114 P1
    lens_sku: L086-MZFD-6.8Z120-DIRECT
    limit_sensor:
      led_off: M120 P0
      led_on: M120 P1
    motor:
      curves:
        focus_inf:
          x:
          - -12.4
          - -11.64
          - -10.89
          - -10.13
          - -9.375
          - -8.619
          - -7.864
          - -7.108
          - -6.352
          - -5.597
          - -4.841
          - -4.086
          - -3.33
          - -2.581
          - -1.825
          - -1.07
          - -0.3142
          - 0.4414
          - 1.197
          - 1.953
          - 2.708
          - 3.464
          - 4.219
          - 4.975
          - 5.73
          - 6.486
          - 7.242
          - 7.997
          - 8.753
          - 9.508
          - 10.26
          - 11.02
          - 11.77
          - 12.53
          - 13.29
          - 14.04
          - 14.8
          - 15.55
          - 16.3
          - 17.06
          - 17.81
          - 18.57
          - 19.32
          - 20.08
          - 20.84
          - 21.59
          - 22.35
          - 23.1
          - 23.86
          - 24.61
          y:
          - -0.3432
          - -1.208
          - -2.002
          - -2.664
          - -3.169
          - -3.543
          - -3.8
          - -3.967
          - -4.039
          - -4.021
          - -3.953
          - -3.818
          - -3.642
          - -3.439
          - -3.205
          - -2.944
          - -2.673
          - -2.38
          - -2.069
          - -1.749
          - -1.434
          - -1.123
          - -0.8119
          - -0.5099
          - -0.2125
          - 0.08497
          - 0.3869
          - 0.6799
          - 0.9593
          - 1.216
          - 1.464
          - 1.721
          - 1.969
          - 2.212
          - 2.442
          - 2.667
          - 2.888
          - 3.1
          - 3.312
          - 3.515
          - 3.713
          - 3.902
          - 4.078
          - 4.254
          - 4.429
          - 4.601
          - 4.772
          - 4.948
          - 5.119
          - 5.29
        focus_ir:
          x:
          - -12.37
          - -11.61
          - -10.85
          - -10.11
          - -9.35
          - -8.594
          - -7.838
          - -7.083
          - -6.327
          - -5.578
          - -4.822
          - -4.067
          - -3.311
          - -2.556
          - -1.806
          - -1.051
          - -0.2953
          - 0.4603
          - 1.216
          - 1.971
          - 2.721
          - 3.476
          - 4.232
          - 4.987
          - 5.743
          - 6.492
          - 7.248
          - 8.003
          - 8.759
          - 9.515
          - 10.26
          - 11.02
          - 11.77
          - 12.53
          - 13.29
          - 14.04
          - 14.79
          - 15.55
          - 16.3
          - 17.06
          - 17.81
          - 18.56
          - 19.32
          - 20.07
          - 20.83
          - 21.58
          - 22.34
          - 23.09
          - 23.85
          - 24.6
          y:
          - -3.93
          - -4.494
          - -4.931
          - -5.278
          - -5.53
          - -5.679
          - -5.688
          - -5.62
          - -5.481
          - -5.314
          - -5.089
          - -4.818
          - -4.53
          - -4.205
          - -3.876
          - -3.538
          - -3.196
          - -2.849
          - -2.497
          - -2.146
          - -1.799
          - -1.465
          - -1.132
          - -0.8028
          - -0.4739
          - -0.1449
          - 0.1706
          - 0.468
          - 0.752
          - 1.036
          - 1.311
          - 1.577
          - 1.829
          - 2.077
          - 2.325
          - 2.564
          - 2.798
          - 3.023
          - 3.24
          - 3.451
          - 3.654
          - 3.853
          - 4.033
          - 4.209
          - 4.384
          - 4.565
          - 4.745
          - 4.925
          - 5.105
          - 5.281
        focus_near:
          x:
          - -12.37
          - -11.61
          - -10.85
          - -10.11
          - -9.35
          - -8.594
          - -7.838
          - -7.083
          - -6.327
          - -5.578
          - -4.822
          - -4.067
          - -3.311
          - -2.556
          - -1.806
          - -1.051
          - -0.2953
          - 0.4603
          - 1.216
          - 1.971
          - 2.721
          - 3.476
          - 4.232
          - 4.987
          - 5.743
          - 6.492
          - 7.248
          - 8.003
          - 8.759
          - 9.515
          - 10.26
          - 11.02
          - 11.77
          - 12.53
          - 13.29
          - 14.04
          - 14.79
          - 15.55
          - 16.3
          - 17.06
          - 17.81
          - 18.56
          - 19.32
          - 20.07
          - 20.83
          - 21.58
          - 22.34
          - 23.09
          - 23.85
          - 24.6
          y:
          - -3.733
          - -4.251
          - -4.738
          - -5.103
          - -5.355
          - -5.503
          - -5.531
          - -5.503
          - -5.4
          - -5.233
          - -5.026
          - -4.76
          - -4.476
          - -4.17
          - -3.837
          - -3.503
          - -3.161
          - -2.819
          - -2.472
          - -2.129
          - -1.791
          - -1.454
          - -1.116
          - -0.7823
          - -0.4535
          - -0.1291
          - 0.1862
          - 0.4835
          - 0.7718
          - 1.051
          - 1.321
          - 1.587
          - 1.844
          - 2.092
          - 2.335
          - 2.569
          - 2.804
          - 3.029
          - 3.245
          - 3.457
          - 3.668
          - 3.862
          - 4.042
          - 4.223
          - 4.398
          - 4.574
          - 4.75
          - 4.925
          - 5.101
          - 5.281
        zoom_correction:
          x:
          - -12.39
          - -11.63
          - -10.86
          - -10.1
          - -9.329
          - -8.567
          - -7.805
          - -7.037
          - -6.275
          - -5.507
          - -4.745
          - -3.977
          - -3.215
          - -2.447
          - -1.685
          - -0.9229
          - -0.1547
          - 0.6071
          - 1.375
          - 2.137
          - 2.905
          - 3.667
          - 4.435
          - 5.197
          - 5.959
          - 6.727
          - 7.489
          - 8.257
          - 9.019
          - 9.787
          - 10.55
          - 11.32
          - 12.08
          - 12.85
          - 13.61
          - 14.38
          - 15.14
          - 15.9
          - 16.67
          - 17.43
          - 18.2
          - 18.96
          - 19.73
          - 20.49
          - 21.26
          - 22.02
          - 22.79
          - 23.55
          - 24.32
          - 25.08
          y:
          - -5.322
          - -3.829
          - -3.04
          - -2.422
          - -1.942
          - -1.538
          - -1.166
          - -0.8197
          - -0.4983
          - -0.1936
          - 0.09864
          - 0.3867
          - 0.6622
          - 0.9252
          - 1.167
          - 1.397
          - 1.614
          - 1.831
          - 2.04
          - 2.24
          - 2.437
          - 2.608
          - 2.779
          - 2.933
          - 3.088
          - 3.234
          - 3.372
          - 3.497
          - 3.614
          - 3.731
          - 3.848
          - 3.961
          - 4.074
          - 4.183
          - 4.266
          - 4.341
          - 4.408
          - 4.479
          - 4.546
          - 4.609
          - 4.676
          - 4.739
          - 4.806
          - 4.877
          - 4.948
          - 5.027
          - 5.103
          - 5.178
          - 5.241
          - 5.307
      default_speed: 1000
      function:
        axis_a: null
        axis_x: Zoom1
        axis_y: Zoom2
        axis_z: Focus
      homing_pulloff:
        value: 0.5
      invert:
        axis_a: false
        axis_x: false
        axis_y: false
        axis_z: false
      range:
        axis_a: null
        axis_x: null
        axis_y: null
        axis_z: null
      speed_list: 2000 1500 *1000 500 200 100 50 10
      step_list: 0.01 0.05 *0.1 0.5 1.0 5.0
    preset:
      p1: -11.67 -4.4 -0.4 --
      p2: -2.7 1.1 -0.6 --
      p3: 2.3 2.6 -1.1 --
      p4: 5.9 3.5 -1.1 --
      p5: 11.5 4.5 3.6 --
    specs:
      focal_length_max: 120
      focal_length_min: 6.8
      image_circle: 9.2
      lpm: 250
logging_level: DEBUG
port: COM149
remember_last_com_port: true
