boot_count: 663
clean_exit: true
com_baud: 115200
com_timeout: 5
controller_feedback_interval: 50
lens:
  L084:
    description: 40x 6.3-252mm 1/1.8"
    filter1:
      name: IR CUT
      state_off:
      - M113 P1
      - M116 P0
      - M117 P1
      - G04 P1
      - M113 P0
      state_on:
      - M113 P1
      - M116 P1
      - M117 P0
      - G04 P1
      - M113 P0
    filter2:
      name: NIR
      state_off:
      - M113 P1
      - M114 P0
      - M115 P1
      - G04 P1
      - M113 P0
      state_on:
      - M113 P1
      - M114 P1
      - M115 P0
      - G04 P1
      - M113 P0
    iris:
      close: G90 G1 A-5 F1000
      open: G90 G1 A0 F1000
    lens_sku: L084-MZFD-6.3Z252-DIRECT
    limit_sensor:
      led_off: M120 P0
      led_on: M120 P1
    motor:
      curves:
        focus_inf:
          color: '#0000FF'
          name: Focus infinity
          pulloff: 0
          x:
          - 34.92
          - 31.92
          - 26.92
          - 21.92
          - 16.92
          - 11.92
          - 6.92
          - 2.92
          - -1.08
          - -5.08
          - -9.08
          - -13.08
          - -16.08
          - -18.08
          - -20.08
          - -21.08
          - -22.08
          - -22.78
          - -23.28
          y:
          - 3.73
          - 4.6
          - 5.94
          - 6.92
          - 7.73
          - 8.12
          - 7.55
          - 6.08
          - 3.77
          - 0.83
          - -2.15
          - -4.3
          - -4.38
          - -2.98
          - -0.14
          - 1.95
          - 4.58
          - 6.78
          - 8.08
        focus_ir:
          color: '#FF0000'
          name: Focus near IR (bad)
          pulloff: 0
          x:
          - -12.2251
          - -7.1551
          - -1.6792
          - 4.7661
          - 12.1472
          - 19.9815
          - 27.6999
          - 32.7645
          - 35.2822
          y:
          - -7.5606
          - -2.0141
          - 3.1353
          - 7.0443
          - 8.3339
          - 7.5149
          - 5.9685
          - 4.6189
          - 3.8827
        focus_near:
          color: '#00FF00'
          name: Focus near (bad)
          pulloff: 0
          x:
          - -23.1883
          - -21.4943
          - -20.0286
          - -18.0775
          - -14.2196
          - -10.9942
          - -6.2888
          - -2.022
          - 2.6832
          - 9.0602
          - 15.7539
          - 22.3352
          - 28.8724
          - 33.1562
          - 35.2822
          y:
          - -1.2947
          - -5.0975
          - -6.6411
          - -7.2323
          - -6.2131
          - -3.9905
          - 0.0035
          - 3.4871
          - 6.4098
          - 8.3122
          - 8.2291
          - 7.1003
          - 5.7355
          - 4.5423
          - 3.8827
        zoom_correction:
          color: '#606060'
          name: Zoom correction
          pulloff: 0
          x:
          - 34.92
          - 31.92
          - 26.92
          - 21.92
          - 16.92
          - 11.92
          - 6.92
          - 2.92
          - -1.08
          - -5.08
          - -9.08
          - -13.08
          - -16.08
          - -18.08
          - -20.08
          - -21.08
          - -22.08
          - -22.78
          - -23.28
          y:
          - -5.31
          - -4.16
          - -2.24
          - -0.41
          - 1.56
          - 3.6
          - 5.21
          - 5.92
          - 5.97
          - 5.29
          - 4.08
          - 2.72
          - 1.84
          - 1.21
          - 0.31
          - -0.22
          - -0.82
          - -1.32
          - -1.62
      default_speed: 1000
      function:
        axis_a: Iris
        axis_x: Zoom1
        axis_y: Focus
        axis_z: Zoom2
      homing_pulloff:
        value: 0.5
      interpolate_count: 250
      range:
        axis_a: null
        axis_x: null
        axis_y: null
        axis_z: null
      reverse:
        axis_a: false
        axis_x: false
        axis_y: false
        axis_z: false
      speed_list: 2000 1500 *1000 500 200 100 50 10
      step_list: 0.01 0.05 *0.1 0.5 1.0 5.0
    preset:
      p1: 34.92 3.75 -5.29 0.0
      p2: 14.8 7.97 2.43 0.0
      p3: -2.5 2.77 5.79 0.0
      p4: -13.5 -4.42 2.59 0.0
      p5: -22.78 6.74 -1.31 0.0
    specs:
      focal_length_max: 252
      focal_length_min: 6.3
      image_circle: 9.2
      lpm: 250
  L086:
    description: 18x 6.8-120mm 1/1.8"
    filter1:
      name: IR CUT
      state_off: G90 G1 A0.7 F1
      state_on: G90 G1 A0.3 F1
    iris:
      close: M114 P0
      open: M114 P1
    lens_sku: L086-MZFD-6.8Z120-DIRECT
    limit_sensor:
      led_off: M120 P0
      led_on: M120 P1
    motor:
      curves:
        focus_inf:
          color: '#0000FF'
          name: Focus infinity
          pulloff: 0
          x: &id001
          - 12.33
          - 9.93
          - 7.29
          - 5.37
          - 2.25
          - 0.09
          - -2.79
          - -4.23
          - -5.67
          - -7.35
          - -8.79
          - -9.99
          - -10.71
          - -11.67
          y:
          - 4.9
          - 4.139
          - 3.182
          - 2.327
          - 0.72
          - -0.416
          - -1.793
          - -2.386
          - -2.854
          - -3.046
          - -3.009
          - -2.388
          - -1.782
          - -0.46
        focus_ir:
          color: '#FF0000'
          name: Focus near IR (bad)
          pulloff: 0
          x:
          - -12.46999949216843
          - -11.28829305520781
          - -9.746216720076708
          - -8.3404372640575
          - -6.670619106412029
          - -1.685905513336141
          - 5.021991503913222
          - 9.714135187398522
          - 12.09000000000005
          y:
          - -3.88269542507344
          - -4.996574212482536
          - -5.68828234498631
          - -5.515428875391146
          - -4.833418733655181
          - -1.702887245837378
          - 1.792754428226117
          - 3.627283343344292
          - 4.470000000000016
        focus_near:
          color: '#00FF00'
          name: Focus near (bad)
          pulloff: 0
          x:
          - -12.46999949216843
          - -9.671695488339065
          - -7.950158530412438
          - -6.367341479579189
          - -0.5248148650601676
          - 5.624319496432681
          - 9.917680703436076
          - 12.09000000000005
          y:
          - -3.628183575923309
          - -5.469228098338353
          - -5.241195572226487
          - -4.541501006034808
          - -0.9231010078596391
          - 2.130438188387246
          - 3.73479827141612
          - 4.470000000000016
        zoom_correction:
          color: '#606060'
          name: Zoom correction
          pulloff: 0
          x: *id001
          y:
          - 5.6
          - 5.268
          - 4.878
          - 4.433
          - 3.576
          - 2.978
          - 2.285
          - 1.937
          - 1.549
          - 1.062
          - 0.106
          - -0.871
          - -1.683
          - -3.1
      default_speed: 1000
      function:
        axis_a: null
        axis_x: Zoom1
        axis_y: Zoom2
        axis_z: Focus
      homing_pulloff:
        value: 0
      interpolate_count: 50
      invert:
        axis_a: false
        axis_x: false
        axis_y: false
        axis_z: false
      range:
        axis_a: null
        axis_x: null
        axis_y: null
        axis_z: null
      speed_list: 2000 1500 *1000 500 200 100 50 10
      step_list: 0.01 0.05 *0.1 0.5 1.0 5.0
    preset:
      p1: 12.33 5.6 4.9 --
      p2: 2.23 3.6 0.7 --
      p3: -2.87 2.3 -1.8 --
      p4: -7.87 0.9 -3.0 --
      p5: -11.67 -3.1 -0.5 --
    specs:
      focal_length_max: 120
      focal_length_min: 6.8
      image_circle: 9.2
      lpm: 250
logging_level: DEBUG
port: COM149
remember_last_com_port: true
