boot_count: 362
clean_exit: true
com_baud: 115200
com_timeout: 5
controller_feedback_interval: 50
lens:
  L084:
    description: 40x 6.3-252mm 1/1.8"
    filter1:
      name: IR CUT
      state_off:
      - M113 P1
      - M116 P1
      - M117 P0
      - G04 P1
      - M113 P0
      state_on:
      - M113 P1
      - M116 P0
      - M117 P1
      - G04 P1
      - M113 P0
    filter2:
      name: NIR
      state_off:
      - M113 P1
      - M114 P1
      - M115 P0
      - G04 P1
      - M113 P0
      state_on:
      - M113 P1
      - M114 P0
      - M115 P1
      - G04 P1
      - M113 P0
    iris:
      close: G90 G1 A-5 F1000
      open: G90 G1 A0 F1000
    lens_sku: L084-MZFD-6.3Z252-DIRECT
    limit_sensor:
      led_off: M120 P0
      led_on: M120 P1
    motor:
      curves:
        focus_inf:
          x:
          - -23.2
          - -22
          - -20.81
          - -19.62
          - -18.43
          - -17.23
          - -16.04
          - -14.85
          - -13.65
          - -12.46
          - -11.26
          - -10.08
          - -8.882
          - -7.686
          - -6.49
          - -5.305
          - -4.109
          - -2.913
          - -1.717
          - -0.5319
          - 0.664
          - 1.86
          - 3.056
          - 4.241
          - 5.437
          - 6.633
          - 7.828
          - 9.014
          - 10.21
          - 11.41
          - 12.6
          - 13.79
          - 14.98
          - 16.18
          - 17.37
          - 18.56
          - 19.76
          - 20.95
          - 22.15
          - 23.33
          - 24.53
          - 25.72
          - 26.92
          - 28.1
          - 29.3
          - 30.5
          - 31.69
          - 32.88
          - 34.07
          - 35.27
          y:
          - 6.41
          - 1.39
          - -0.626
          - -1.86
          - -2.6
          - -3.08
          - -3.32
          - -3.31
          - -3.14
          - -2.79
          - -2.27
          - -1.65
          - -0.859
          - -0.0256
          - 0.857
          - 1.73
          - 2.6
          - 3.45
          - 4.21
          - 4.92
          - 5.6
          - 6.18
          - 6.69
          - 7.16
          - 7.53
          - 7.85
          - 8.08
          - 8.23
          - 8.33
          - 8.38
          - 8.37
          - 8.31
          - 8.19
          - 8.05
          - 7.88
          - 7.69
          - 7.52
          - 7.3
          - 7.08
          - 6.86
          - 6.63
          - 6.42
          - 6.19
          - 5.96
          - 5.7
          - 5.45
          - 5.18
          - 4.85
          - 4.48
          - 4.08
        focus_ir:
          x:
          - -11.99
          - -11.03
          - -10.07
          - -9.104
          - -8.141
          - -7.167
          - -6.204
          - -5.241
          - -4.278
          - -3.315
          - -2.352
          - -1.389
          - -0.426
          - 0.537
          - 1.5
          - 2.474
          - 3.437
          - 4.4
          - 5.363
          - 6.326
          - 7.289
          - 8.252
          - 9.215
          - 10.18
          - 11.14
          - 12.11
          - 13.08
          - 14.04
          - 15
          - 15.97
          - 16.93
          - 17.89
          - 18.86
          - 19.82
          - 20.78
          - 21.76
          - 22.72
          - 23.68
          - 24.64
          - 25.61
          - 26.57
          - 27.53
          - 28.5
          - 29.46
          - 30.42
          - 31.4
          - 32.36
          - 33.32
          - 34.29
          - 35.25
          y:
          - -6.3
          - -5.26
          - -4.29
          - -3.32
          - -2.36
          - -1.42
          - -0.489
          - 0.442
          - 1.29
          - 2.12
          - 2.9
          - 3.62
          - 4.28
          - 4.92
          - 5.48
          - 5.98
          - 6.44
          - 6.84
          - 7.2
          - 7.51
          - 7.73
          - 7.93
          - 8.06
          - 8.16
          - 8.22
          - 8.22
          - 8.19
          - 8.13
          - 8.06
          - 7.99
          - 7.86
          - 7.71
          - 7.58
          - 7.42
          - 7.26
          - 7.11
          - 6.94
          - 6.76
          - 6.58
          - 6.39
          - 6.21
          - 6.03
          - 5.85
          - 5.65
          - 5.42
          - 5.2
          - 4.97
          - 4.71
          - 4.38
          - 4.04
        focus_near:
          x:
          - -23.19
          - -21.99
          - -20.81
          - -19.61
          - -18.42
          - -17.23
          - -16.04
          - -14.84
          - -13.64
          - -12.46
          - -11.26
          - -10.07
          - -8.882
          - -7.686
          - -6.49
          - -5.305
          - -4.109
          - -2.913
          - -1.728
          - -0.5319
          - 0.664
          - 1.86
          - 3.045
          - 4.241
          - 5.437
          - 6.622
          - 7.818
          - 9.014
          - 10.2
          - 11.39
          - 12.59
          - 13.79
          - 14.97
          - 16.17
          - 17.36
          - 18.55
          - 19.74
          - 20.94
          - 22.13
          - 23.32
          - 24.52
          - 25.7
          - 26.9
          - 28.09
          - 29.29
          - 30.48
          - 31.67
          - 32.87
          - 34.05
          - 35.25
          y:
          - -0.744
          - -3.51
          - -4.99
          - -5.89
          - -6.22
          - -6.23
          - -5.96
          - -5.56
          - -4.92
          - -4.23
          - -3.42
          - -2.53
          - -1.59
          - -0.629
          - 0.332
          - 1.25
          - 2.19
          - 3.09
          - 3.92
          - 4.67
          - 5.38
          - 6
          - 6.54
          - 7.03
          - 7.44
          - 7.77
          - 7.99
          - 8.18
          - 8.28
          - 8.33
          - 8.32
          - 8.27
          - 8.15
          - 8.01
          - 7.84
          - 7.67
          - 7.48
          - 7.27
          - 7.06
          - 6.84
          - 6.62
          - 6.4
          - 6.18
          - 5.95
          - 5.7
          - 5.43
          - 5.17
          - 4.86
          - 4.47
          - 4.06
        zoom_correction:
          x:
          - -23.18
          - -21.98
          - -20.8
          - -19.6
          - -18.41
          - -17.22
          - -16.02
          - -14.83
          - -13.63
          - -12.45
          - -11.25
          - -10.06
          - -8.871
          - -7.675
          - -6.479
          - -5.294
          - -4.098
          - -2.902
          - -1.717
          - -0.5213
          - 0.6746
          - 1.87
          - 3.056
          - 4.252
          - 5.447
          - 6.633
          - 7.828
          - 9.024
          - 10.21
          - 11.41
          - 12.6
          - 13.8
          - 14.98
          - 16.18
          - 17.37
          - 18.56
          - 19.76
          - 20.95
          - 22.14
          - 23.33
          - 24.53
          - 25.71
          - 26.91
          - 28.1
          - 29.3
          - 30.49
          - 31.68
          - 32.88
          - 34.06
          - 35.26
          y:
          - -1.71
          - -0.84
          - -0.216
          - 0.323
          - 0.724
          - 1.14
          - 1.54
          - 1.89
          - 2.26
          - 2.62
          - 3.02
          - 3.42
          - 3.82
          - 4.19
          - 4.54
          - 4.91
          - 5.16
          - 5.37
          - 5.51
          - 5.58
          - 5.59
          - 5.53
          - 5.42
          - 5.26
          - 5.02
          - 4.73
          - 4.38
          - 4.03
          - 3.65
          - 3.21
          - 2.76
          - 2.31
          - 1.81
          - 1.33
          - 0.83
          - 0.333
          - -0.153
          - -0.639
          - -1.09
          - -1.54
          - -1.97
          - -2.39
          - -2.81
          - -3.22
          - -3.64
          - -4.08
          - -4.5
          - -5
          - -5.5
          - -6.01
      default_speed: 1000
      function:
        axis_a: Iris
        axis_x: Zoom1
        axis_y: Focus
        axis_z: Zoom2
      homing_pulloff:
        value: 0.5
      range:
        axis_a: null
        axis_x: null
        axis_y: null
        axis_z: null
      reverse:
        axis_a: false
        axis_x: false
        axis_y: false
        axis_z: false
      speed_list: 2000 1500 *1000 500 200 100 50 10
      step_list: 0.01 0.05 *0.1 0.5 1.0 5.0
    preset:
      p1: 34.45 3.05 -6.4 0.0
      p2: 12.5 7.55 2.19 0.0
      p3: -0.4 4.0 5.08 0.0
      p4: -14.26 -4.6 1.65 0.0
      p5: -21.18 2.25 -0.73 0.0
    specs:
      focal_length_max: 252
      focal_length_min: 6.3
      image_circle: 9.2
      lpm: 250
  L085:
    description: 25x 5.3-130mm 1/2.7"
    filter1:
      name: IR CUT
      state_off: G90 G1 A0.7 F1
      state_on: G90 G1 A0.3 F1
    iris:
      close: M114 P0
      open: M114 P1
    lens_sku: L085-MZFD-5.3Z130-DIRECT
    limit_sensor:
      led_off: M120 P0
      led_on: M120 P1
    motor:
      default_speed: 1000
      function:
        axis_a: null
        axis_x: Zoom
        axis_y: Focus
        axis_z: null
      homing_pulloff:
        value: 0.5
      range:
        axis_a: null
        axis_x: null
        axis_y: null
        axis_z: null
      reverse:
        axis_a: false
        axis_x: false
        axis_y: false
        axis_z: false
      speed_list: 2000 1500 *1000 500 200 100 50 10
      step_list: 0.01 0.05 *0.1 0.5 1.0 5.0
    preset:
      p1: -9.0 0.3 -- --
      p2: -2.0 -1.9 -- --
      p3: 1.0 -3.0 -- --
      p4: 4.0 -3.8 -- --
      p5: 9.5 -1.3 -- --
    specs:
      focal_length_max: 130
      focal_length_min: 5.3
      image_circle: 6.8
      lpm: 250
  L086:
    description: 18x 6.8-120mm 1/1.8"
    filter1:
      name: IR CUT
      state_off: G90 G1 A0.7 F1
      state_on: G90 G1 A0.3 F1
    iris:
      close: M114 P0
      open: M114 P1
    lens_sku: L086-MZFD-6.8Z120-DIRECT
    limit_sensor:
      led_off: M120 P0
      led_on: M120 P1
    motor:
      curves:
        focus_inf:
          x:
          - -12.4
          - -11.64
          - -10.89
          - -10.13
          - -9.375
          - -8.619
          - -7.864
          - -7.108
          - -6.352
          - -5.597
          - -4.841
          - -4.086
          - -3.33
          - -2.581
          - -1.825
          - -1.07
          - -0.3142
          - 0.4414
          - 1.197
          - 1.953
          - 2.708
          - 3.464
          - 4.219
          - 4.975
          - 5.73
          - 6.486
          - 7.242
          - 7.997
          - 8.753
          - 9.508
          - 10.26
          - 11.02
          - 11.77
          - 12.53
          - 13.29
          - 14.04
          - 14.8
          - 15.55
          - 16.3
          - 17.06
          - 17.81
          - 18.57
          - 19.32
          - 20.08
          - 20.84
          - 21.59
          - 22.35
          - 23.1
          - 23.86
          - 24.61
          y:
          - -0.3432
          - -1.208
          - -2.002
          - -2.664
          - -3.169
          - -3.543
          - -3.8
          - -3.967
          - -4.039
          - -4.021
          - -3.953
          - -3.818
          - -3.642
          - -3.439
          - -3.205
          - -2.944
          - -2.673
          - -2.38
          - -2.069
          - -1.749
          - -1.434
          - -1.123
          - -0.8119
          - -0.5099
          - -0.2125
          - 0.08497
          - 0.3869
          - 0.6799
          - 0.9593
          - 1.216
          - 1.464
          - 1.721
          - 1.969
          - 2.212
          - 2.442
          - 2.667
          - 2.888
          - 3.1
          - 3.312
          - 3.515
          - 3.713
          - 3.902
          - 4.078
          - 4.254
          - 4.429
          - 4.601
          - 4.772
          - 4.948
          - 5.119
          - 5.29
        focus_ir:
          x:
          - -12.37
          - -11.61
          - -10.85
          - -10.11
          - -9.35
          - -8.594
          - -7.838
          - -7.083
          - -6.327
          - -5.578
          - -4.822
          - -4.067
          - -3.311
          - -2.556
          - -1.806
          - -1.051
          - -0.2953
          - 0.4603
          - 1.216
          - 1.971
          - 2.721
          - 3.476
          - 4.232
          - 4.987
          - 5.743
          - 6.492
          - 7.248
          - 8.003
          - 8.759
          - 9.515
          - 10.26
          - 11.02
          - 11.77
          - 12.53
          - 13.29
          - 14.04
          - 14.79
          - 15.55
          - 16.3
          - 17.06
          - 17.81
          - 18.56
          - 19.32
          - 20.07
          - 20.83
          - 21.58
          - 22.34
          - 23.09
          - 23.85
          - 24.6
          y:
          - -3.93
          - -4.494
          - -4.931
          - -5.278
          - -5.53
          - -5.679
          - -5.688
          - -5.62
          - -5.481
          - -5.314
          - -5.089
          - -4.818
          - -4.53
          - -4.205
          - -3.876
          - -3.538
          - -3.196
          - -2.849
          - -2.497
          - -2.146
          - -1.799
          - -1.465
          - -1.132
          - -0.8028
          - -0.4739
          - -0.1449
          - 0.1706
          - 0.468
          - 0.752
          - 1.036
          - 1.311
          - 1.577
          - 1.829
          - 2.077
          - 2.325
          - 2.564
          - 2.798
          - 3.023
          - 3.24
          - 3.451
          - 3.654
          - 3.853
          - 4.033
          - 4.209
          - 4.384
          - 4.565
          - 4.745
          - 4.925
          - 5.105
          - 5.281
        focus_near:
          x:
          - -12.37
          - -11.61
          - -10.85
          - -10.11
          - -9.35
          - -8.594
          - -7.838
          - -7.083
          - -6.327
          - -5.578
          - -4.822
          - -4.067
          - -3.311
          - -2.556
          - -1.806
          - -1.051
          - -0.2953
          - 0.4603
          - 1.216
          - 1.971
          - 2.721
          - 3.476
          - 4.232
          - 4.987
          - 5.743
          - 6.492
          - 7.248
          - 8.003
          - 8.759
          - 9.515
          - 10.26
          - 11.02
          - 11.77
          - 12.53
          - 13.29
          - 14.04
          - 14.79
          - 15.55
          - 16.3
          - 17.06
          - 17.81
          - 18.56
          - 19.32
          - 20.07
          - 20.83
          - 21.58
          - 22.34
          - 23.09
          - 23.85
          - 24.6
          y:
          - -3.733
          - -4.251
          - -4.738
          - -5.103
          - -5.355
          - -5.503
          - -5.531
          - -5.503
          - -5.4
          - -5.233
          - -5.026
          - -4.76
          - -4.476
          - -4.17
          - -3.837
          - -3.503
          - -3.161
          - -2.819
          - -2.472
          - -2.129
          - -1.791
          - -1.454
          - -1.116
          - -0.7823
          - -0.4535
          - -0.1291
          - 0.1862
          - 0.4835
          - 0.7718
          - 1.051
          - 1.321
          - 1.587
          - 1.844
          - 2.092
          - 2.335
          - 2.569
          - 2.804
          - 3.029
          - 3.245
          - 3.457
          - 3.668
          - 3.862
          - 4.042
          - 4.223
          - 4.398
          - 4.574
          - 4.75
          - 4.925
          - 5.101
          - 5.281
        zoom_correction:
          x:
          - -12.39
          - -11.63
          - -10.86
          - -10.1
          - -9.329
          - -8.567
          - -7.805
          - -7.037
          - -6.275
          - -5.507
          - -4.745
          - -3.977
          - -3.215
          - -2.447
          - -1.685
          - -0.9229
          - -0.1547
          - 0.6071
          - 1.375
          - 2.137
          - 2.905
          - 3.667
          - 4.435
          - 5.197
          - 5.959
          - 6.727
          - 7.489
          - 8.257
          - 9.019
          - 9.787
          - 10.55
          - 11.32
          - 12.08
          - 12.85
          - 13.61
          - 14.38
          - 15.14
          - 15.9
          - 16.67
          - 17.43
          - 18.2
          - 18.96
          - 19.73
          - 20.49
          - 21.26
          - 22.02
          - 22.79
          - 23.55
          - 24.32
          - 25.08
          y:
          - -5.322
          - -3.829
          - -3.04
          - -2.422
          - -1.942
          - -1.538
          - -1.166
          - -0.8197
          - -0.4983
          - -0.1936
          - 0.09864
          - 0.3867
          - 0.6622
          - 0.9252
          - 1.167
          - 1.397
          - 1.614
          - 1.831
          - 2.04
          - 2.24
          - 2.437
          - 2.608
          - 2.779
          - 2.933
          - 3.088
          - 3.234
          - 3.372
          - 3.497
          - 3.614
          - 3.731
          - 3.848
          - 3.961
          - 4.074
          - 4.183
          - 4.266
          - 4.341
          - 4.408
          - 4.479
          - 4.546
          - 4.609
          - 4.676
          - 4.739
          - 4.806
          - 4.877
          - 4.948
          - 5.027
          - 5.103
          - 5.178
          - 5.241
          - 5.307
      default_speed: 1000
      function:
        axis_a: null
        axis_x: Zoom1
        axis_y: Zoom2
        axis_z: Focus
      homing_pulloff:
        value: 0.5
      range:
        axis_a: null
        axis_x: null
        axis_y: null
        axis_z: null
      reverse:
        axis_a: false
        axis_x: false
        axis_y: false
        axis_z: false
      speed_list: 2000 1500 *1000 500 200 100 50 10
      step_list: 0.01 0.05 *0.1 0.5 1.0 5.0
    preset:
      p1: -12.37 -4.6 -3.0 --
      p2: -3.3 -3.9 -0.2 --
      p3: 4.6 -1.4 4.2 --
      p4: 8.6 0.6 5.3 --
      p5: 11.6 3.5 2.8 --
    specs:
      focal_length_max: 120
      focal_length_min: 6.8
      image_circle: 9.2
      lpm: 250
logging_level: DEBUG
port: COM149
remember_last_com_port: true
